# Generated by Django 4.1.7 on 2023-05-08 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_produit_price'),
    ]

    operations = [
    ]
